"""Regression tests against the canonical original implementation.

These tests load the golden output fixtures generated by running the original
``morphel_tokenizer.py`` script over ``tiny_corpus.txt``. We run the refactored
components over the same inputs and assert exact parity.
"""

from __future__ import annotations

import pytest

from morphel.mi import build_global_mi_index
from morphel.preprocessing import collect_word_frequencies, simple_tokenize
from morphel.segmentation import build_segmentation_cache
from morphel.vocabulary import build_character_alphabet, build_vocabulary, count_contiguous_spans


def test_segmentation_cache_matches_canonical(
    tiny_corpus: list[str],
    golden_segmentations: dict[str, list[str]],
) -> None:
    """Verify that the T=0 segmentation cache matches the canonical exact output."""
    word_freq = collect_word_frequencies(tiny_corpus, simple_tokenize)
    vowels = set("aeiouAEIOUıİöüÖÜâîûÂÎÛéèêëàâîïôùûüÿœŒаеёиоуыэюяАЕЁИОУЫЭЮЯ")

    mi_index = build_global_mi_index(
        word_freq,
        vowels,
        mi_threshold=0.0,
        use_vowel_boundary_filter=True,
    )

    # Seed numpy for deterministic T=0 behavior (argmax) just to be safe
    from morphel.sampling import set_seed
    set_seed(42)

    cache = build_segmentation_cache(word_freq.keys(), mi_index, top_k=4)

    # Must match exactly, including the order of pieces
    for word, expected_pieces in golden_segmentations.items():
        assert cache[word] == expected_pieces, f"Mismatch on word: {word}"

    # Must contain exactly the same set of keys
    assert set(cache.keys()) == set(golden_segmentations.keys())


def test_vocabulary_matches_canonical(
    tiny_corpus: list[str],
    golden_segmentations: dict[str, list[str]],
    tiny_vocab: dict[str, int],
) -> None:
    """Verify that the final vocabulary matches the canonical exact output."""
    word_freq = collect_word_frequencies(tiny_corpus, simple_tokenize)
    spans = count_contiguous_spans(word_freq, golden_segmentations)
    alphabet = build_character_alphabet(word_freq.keys())

    vocab, _ = build_vocabulary(
        subword_frequency=spans,
        character_alphabet=alphabet,
        vocab_size=100,
        min_frequency=1,
    )

    # Dictionary keys and values must match exactly.
    # Note: Insertion order matters for Hugging Face tokenizers, so we assert
    # the dictionaries match exactly in structure and content.
    assert vocab == tiny_vocab
